### ISSUE TITLE
Не знаю как правильно сделать пулреквест

### ISSUE THREAD

**Issue by maxyc** [yiisoft/yii2-authclient#17]
в файле clients/vkontakte нет возможности изменять поля, которые нужны для запроса у соцсети. предлагаю добавить свойство

```public $userAttributes = 'uid,first_name,last_name,nickname,screen_name,sex,bdate,city,country,timezone,photo_max_orig,occupation,activities';```

и его обработку
```
    /**
     * @inheritdoc
     */
    protected function initUserAttributes()
    {
        $response = $this->api('users.get.json', 'GET', [
            'fields' => $this->userAttributes
        ]);```

тогда сможем настраивать нужные поля )

**Comment by mourahi** [comment]
Good Idea, thanks. Can'i ask about the uri in Google  : 
I have basic yii2, and i'am in Localhost. what's the code uri to put in "https://console.developers.google.com"  . because i try "http://localhost" and it's not match : 
-------------------------------
400. That’s an error.
Error: redirect_uri_mismatch
-----------------------------

No problem in facebook, but no way with Google !!

**Comment by klimov-paul** [comment]
Resolved by commit 2fbb4ca

**Comment by klimov-paul** [comment]
c605e5b

**Comment by klimov-paul** [comment]
c605e5b
