### ISSUE TITLE
Vkontakte oauth yii\base\ErrorException

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii2-authclient#185]
### What steps will reproduce the problem?

send 

              {
			response: {
				error: {
					error_code: 5, 
					error_msg: [Filtered], 
					request_params: Array of length 4
				}, 
				response: null
			}
		}

in  https://github.com/yiisoft/yii2-authclient/blob/master/clients/VKontakte.php#L88

### What's expected?

correct warning processing

        $attributes = [];
        if (!empty($response['response'])) {
            $attributes = array_shift($response['response']);
        }

### What do you get instead?

yii\base\ErrorException
array_shift() expects parameter 1 to be array, null given

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             |  2.0.12
| Yii Auth Client version | 2.1.0
| Yii HTTP Client version | 2.0.2
| PHP version             | 7.1
| Operating system        | linux

**Comment by klimov-paul** [comment]
Overall current behavior is correct - it throws exception on remote request failure.
Suggested fix is incorrect as it hides the problem from the developer.
The only improvement, which can be made is composition of more verbose exception, which will use error message from response instead of simple PHP error.

**Comment by klimov-paul** [comment]
Resolved by commit cae31f1ccd7f82f701c11440244f728dd46b3bd9
