### ISSUE TITLE
Ability to disable sessions

### ISSUE THREAD

**Issue by webleaf** [yiisoft/yii2-authclient#205]
How fully disable sessions (using authclient with REST)? It send cookie always.

https://github.com/yiisoft/yii2-authclient/blob/52325938e90bb3a1f8ca72c7192f11feb612cdd6/src/SessionStateStorage.php#L32-L52

**Comment by webleaf** [comment]
Sorry for question. I thought it's some thing like "docs bug". Because docs says:
> If not set - application 'session' component will be used, but only, if it is available (e.g. in web application), otherwise - no session will be used and no data saving will be performed.

But there are no way to disable sessions via configuration (don't see that possibility) in web application.
So i do that. It it ok?

```
namespace api\components;

class DummyStateStorage extends \yii\authclient\SessionStateStorage
{
    public function init()
    {
        $this->session = null;
    }
}
```

```
'authClientCollection' => [
    'class' => 'yii\authclient\Collection',
    'clients' => [
        'yandex' => [
            'class' => 'yii\authclient\clients\Yandex',
            'clientId' => 'any-client-id',
            'clientSecret' => 'any-client-secret',
            'validateAuthState' => false,
            'stateStorage' => [
                'class' => 'api\components\DummyStateStorage'
            ],
        ],
    ],
],
```

**Comment by webleaf** [comment]
It could be feature requests:
- need possibility for disabling sessions
- need possibility for getting access_token in successCallback instead of saving it via setState()

**Comment by SamMousa** [comment]
I like the idea, note that an alternative storage is also needed for the auth state parameter.

**Comment by tunecino** [comment]
When doing REST app you may also need a different workflow, like instead of Yii redirecting to Client, you may need Yii to only provide the generated url to frontend instead, then frontend redirects to Client, Client redirects back to frontend, then frontend sends received params to Yii.

For that and for the non use of Session I did the following which replaces Session by Cache:

1. Create `app\components\AuthAction` that extends `yii\authclient\AuthAction` and make your controller using it:

```php
public function actions()
{
    return [
        'client' => [
            'class' => 'app\components\AuthAction',
            'successCallback' => [$this, 'onAuthSuccess'],
        ],
    ];
}
```
In your new Action, depending on which clients you use, you may only need to override `authOAuth2($client, $authUrlParams = [])`. Just copy/past original method code and make 2 changes:

1. ensure it returns the generated url (`$client->buildAuthUrl($authUrlParams)]`) instead of performing the redirect.

2. add the following line somewhere on top:
```php
$client->setStateStorage('app\components\CacheStateStorage');
```

3. create that `app\components\CacheStateStorage` with following content:

```php
namespace app\components;

use Yii;
use yii\base\Component;
use yii\di\Instance;
use yii\authclient\StateStorageInterface;

class CacheStateStorage extends Component implements StateStorageInterface
{
    public $cache = 'cache';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();
        $this->cache = Instance::ensure($this->cache, 'yii\caching\CacheInterface');
    }

    /**
     * {@inheritdoc}
     */
    public function set($key, $value)
    {
        $this->cache->set($key, $value);
    }

    /**
     * {@inheritdoc}
     */
    public function get($key)
    {
        return $this->cache->get($key);
    }

    /**
     * {@inheritdoc}
     */
    public function remove($key)
    {
        return $this->cache->delete($key);
    }
}
```

That should solve both issues.
