### ISSUE TITLE
Detect Logout?

### ISSUE THREAD

**Issue by gallexme** [yiisoft/yii2-authclient#227]
### What steps will reproduce the problem?
Login with Yii
Logout at the Authprovider example: Keycloak
open Yii App, still logged  in wtf?
### What's expected?
when i logout from Keycloak i should be logged out from any app(Single Sign On)
### What do you get instead?
Im Still logged in in Yii

**Comment by samdark** [comment]
Do you have "remember me" active?

**Comment by gallexme** [comment]
@samdark tried both, does not work

**Comment by jakim** [comment]
Are you sure it is related to Yii? If you use Keycloak, much depends on integration.
If you log out in the provider's panel, the application in Yii must receive a signal that the user has logged out.

**Comment by annaDostoevskaya** [comment]
The logout endpoint requires you to provide an ID token. 
The OAuthToken interface has no way to get it.

**Comment by samdark** [comment]
Seems it's solvable. Closing. Thanks, @annaDostoevskaya

**Comment by azmeuk** [comment]
>  If you log out in the provider's panel, the application in Yii must receive a signal that the user has logged out.

@jakim I am not sure what you mean by signal? Does the IdP should redirect to a given endpoint on the Yii app (after logout on the IdP) in the fashion of [RP Initiated Logout](https://github.com/yiisoft/yii2-authclient/issues/361)?

@annaDostoevskaya Can you give some more details on how you solved this?

**Comment by annaDostoevskaya** [comment]
@jakim mb it's can help you https://openid.net/specs/openid-connect-rpinitiated-1_0.html ?

**Comment by annaDostoevskaya** [comment]
@azmeuk 
in fact, I just pass a redirect to the keylock side and when the authorization server logs out the session and redirects me back to my web application, I delete the session to myself.  this is dumb and error prone because you will stay in the application if you close the browser window at the time of the redirect.

you can try a javascript code that communicates with the authorization server and checks for active sessions there, after which it directs your user to login to the system, But I don't remember where he is.
