### ISSUE TITLE
UnknownMethodException when used in console app

### ISSUE THREAD

**Issue by andrei-livadariu** [yiisoft/yii2-authclient#25]
We have encountered a problem with our app when using the authclient (specifically LinkedIn) within a console app. Our use case is the following: we post messages to LinkedIn using a cron job. In order to do this, we save the user's auth token in the database and load it whenever needed.

When setting up LinkedIn within the console (before any message is actually posted), we use the following code:

    $authClients = \Yii::$app->get('authClientCollection');
    $linkedIn = $authClients->getClient('linkedin');
    $linkedIn->setAccessToken([
        'params' => $authToken, // The $authToken parameter is coming from the database
                                // and it is in the correct format; this works in the web app
    ]);

The exception thrown is of type `UnknownMethodException`:

    Calling unknown method: yii\console\Application::getSession()

It is thrown by the `setAcessToken` method, because internally it calls `saveAccessToken`, which in turn tries to retrieve the session from the app. Since console apps have no session, this call fails. We have tried to set up a session component for the console app, but this won't solve it either, because instead of using `Yii::$app->session` (which is resolved by Yii's magic methods) the code calls `Yii::$app->getSession()` which fails.

Please note that in our particular use case we never actually need to save the access token in the session, as we are not using the authentication flow in this scenario.

**Comment by klimov-paul** [comment]
Resolved by commit 152616d

**Comment by vaibhav-ranosys** [comment]
Hello,

I have a problem with linkedin login specifically because facebook login works fine. In linkedin login, it every time states that invalid redirect uri in the linkedin popup which opens. I don't know what's the problem or I am doing anything wrong. can you help me on this. Below are the details

Project Folder : localhost/projects/myproject/
Url for linkedin login : localhost/projects/myproject/frontend/login
Redirect uri at linkedin : localhost/projects/myproject/frontend/login
Controller details : 
public function actions()
    {
        return [
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'successCallback'],
            ],
        ];
    }

    public function successCallback($client)
    {
         $attributes = $client->getUserAttributes();
         echo '<pre>';print_r($attributes);exit; // to print the information.
    } 

This works fine for facebook but not for linkedin. Below is the error screenshot
![linkedin_error](https://cloud.githubusercontent.com/assets/10459070/7806807/cdc3a3f2-03a2-11e5-8b3a-b5f998ef5a14.png)

**Comment by andrei-livadariu** [comment]
Have you declared your redirect_uri on LinkedIn's developer site?

In the same place where you created your app there is a field where you can write one or more URLs where your app can redirect to. The thing is, you need to redirect to one of those URLs exactly - no query parameters, no extra subdomains, no extra folder structure. Otherwise the query will fail with the same message you see above.

I was running into this problem before because my URL had a user id parameter and LinkedIn refused that. I had to put it into the session and read it from there on the redirect page in order to get it to work.

**Comment by vaibhav-ranosys** [comment]
Yes, I have declared a redirect_uri at linkedin apps page as defined in above comment.
Redirect uri at linkedin : localhost/projects/myproject/frontend/login

I am also confused over this. Is this redirect uri at linkedin not the correct one.

**Comment by andrei-livadariu** [comment]
You can try putting http:// as part of the redirect URL declared on LinkedIn.
I can't know for sure, but I wouldn't be surprised if they didn't support localhost for redirects.

**Comment by vaibhav-ranosys** [comment]
Yes I have tried by adding http:// and https:// both for the localhost redirect uri at linkedin app. By the way it works with localhost because it works for facebook and developer link of linkedin also states this https://developer.linkedin.com/docs/oauth2

**Comment by vaibhav-ranosys** [comment]
Hello

Ok I got it. The problem was that in the view file we have to put the code like 
echo yii\authclient\widgets\AuthChoice::widget([
     'baseAuthUrl' => ['login/auth']
]);  to activate the login buttons

Previously i was setting redirect url in app to http://localhost/projects/myproject/frontend/login but as in baseAuthUrl it is set to login/auth so i have to set the redirect url to http://localhost/projects/myproject/frontend/login/auth and it did the trick.
